// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <openpmdPluginInfo.h>
#include <avtopenpmdFileFormat.h>
#include <avtMTMDFileFormatInterface.h>
#include <avtGenericDatabase.h>

// ****************************************************************************
//  Method:  openpmdCommonPluginInfo::GetDatabaseType
//
//  Purpose:
//    Returns the type of a openpmd database.
//
//  Programmer:  generated by xml2info
//  Creation:    omitted
//
// ****************************************************************************
DatabaseType
openpmdCommonPluginInfo::GetDatabaseType()
{
    return DB_TYPE_MTSD;
}

// ****************************************************************************
//  Method: openpmdCommonPluginInfo::SetupDatabase
//
//  Purpose:
//      Sets up a openpmd database.
//
//  Arguments:
//      list    A list of file names.
//      nList   The number of timesteps in list.
//      nBlocks The number of blocks in the list.
//
//  Returns:    A openpmd database from list.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabase *
openpmdCommonPluginInfo::SetupDatabase(const char *const *list,
                                   int nList, int nBlock)
{
    if (nBlock <= 0)
    {
        nBlock = 1;
    }
    int nTimestepGroups = nList / nBlock;
    if (nTimestepGroups <= 0)
    {
        nTimestepGroups = 1;
    }

    avtMTMDFileFormat **ffl = new avtMTMDFileFormat *[nTimestepGroups];
    for (int i = 0; i < nTimestepGroups; i++)
    {
        const int index = i * nBlock;
        ffl[i] = new avtopenpmdFileFormat(list[index]);
    }
    avtMTMDFileFormatInterface *inter
           = new avtMTMDFileFormatInterface(ffl, nTimestepGroups);
    return new avtGenericDatabase(inter);
}
