// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <openpmdPluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(openpmd,Engine)

// ****************************************************************************
//  Method: openpmdEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a openpmd writer.
//
//  Returns:    A openpmd writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
openpmdEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

