OpenDatabase("/Users/benwibking/openpmd-api-plugin/example_data/bp5_2d.pmd")
AddPlot("Pseudocolor", "gasDensity")
DrawPlots()
Query("NumZones")
print("NumZones before InverseGhost", GetQueryOutputValue())
AddOperator("InverseGhostZone")
DrawPlots()
Query("NumZones")
print("NumZones after InverseGhost", GetQueryOutputValue())
DeleteAllPlots()
